import Head from 'next/head'
import React from 'react'
import Layout from '../components/Layout/Layout';

import { useRequest } from '../hooks/useHttp';

export default function Home() {

  async function handleClick(event: React.MouseEvent) {
    const data = await useRequest({
      url: '/posts',
      method: 'GET'
    })

  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}